# author @ Sarthak Chauhan

#A X = B
#[10, -1, 2, 0 ][a] [6]
#[-1, 11, -1, 3][b]=[25]
#[2, -1, 10, -1][c] [-11]
#[0, 3, -1, 8[d] [15]

Gaussian Elimination 

In [25]:

def gauss(A):
    n = len(A)

    for i in range(0, n):
        # Search for maximum in this column
        maxEl = abs(A[i][i])
        maxRow = i
        for k in range(i + 1, n):
            if abs(A[k][i]) > maxEl:
                maxEl = abs(A[k][i])
                maxRow = k

        # Swap maximum row with current row (column by column)
        for k in range(i, n + 1):
            tmp = A[maxRow][k]
            A[maxRow][k] = A[i][k]
            A[i][k] = tmp

        # Make all rows below this one 0 in current column
        for k in range(i + 1, n):
            c = -A[k][i] / A[i][i]
            for j in range(i, n + 1):
                if i == j:
                    A[k][j] = 0
                else:
                    A[k][j] += c * A[i][j]

    # Solve equation Ax=b for an upper triangular matrix A
    x = [0 for i in range(n)]
    for i in range(n - 1, -1, -1):
        x[i] = A[i][n] / A[i][i]
        for k in range(i - 1, -1, -1):
            A[k][n] -= A[k][i] * x[i]
    return x



In [26]:
#Equally distributed maxtrix Display
def pprint(A):
    n = len(A)
    for i in range(0, n):
        line = ""
        for j in range(0, n + 1):
            line += str(A[i][j]) + "\t"
            if j == n - 1:
                line += "| "
        print(line)
    print("")


In [27]:

if __name__ == "__main__":
    A=[[10, -1, 2, 0, 6],[-1, 11, -1, 3, 25],[2, -1, 10, -1, -11],[0, 3, -1, 8, 15]]
    
    print("Augumented Matrix")
    pprint(A)
    # Calculate solution
    x = gauss(A)

    line = "Result:\t"
    for i in range(0, len(A)):
        line += str(x[i]) + "\t"
    print(line)
    
    # Comparison 1
    a=np.asarray([[10, -1, 2, 0],[-1, 11, -1, 3],[2, -1, 10, -1],[0, 3, -1, 8]])
    b = np.asarray([6,25,-11,15]) 
    
    t=np.linalg.inv(a)
    x=b@t
    print("Comparison 1: Inv(A)*B")
    print(x)

Augumented Matrix
10	-1	2	0	| 6	
-1	11	-1	3	| 25	
2	-1	10	-1	| -11	
0	3	-1	8	| 15	

Result:	1.0	2.0	-1.0	0.9999999999999999	
Comparison 1: Inv(A)*B
[ 1.  2. -1.  1.]


Jacobian Elimination

In [ ]:
import numpy as np

In [46]:
#Jacobian Elimination function
def GaussJacobi(A, b, n):
    # create a 1d matrix with n zeores
    x=np.zeros(len(A[0]))

    #getting the diagonal elements
    d=np.diag(A)
    # substract A from w
    # w a two-dimensional array with the flattened input as a diagonal d
    r=A-np.diagflat(d)

    # Iterating to get the new values of x
    # started with [0,0,0,0]
    for i in range(0,n):
      x=(b- np.dot(r,x))/d
      print("Loop" +str(i+1))
      print(x)
    return x


In [47]:

a=np.asarray([[10, -1, 2, 0],[-1, 11, -1, 3],[2, -1, 10, -1],[0, 3, -1, 8]])
b = np.asarray([6,25,-11,15])

t=(GaussJacobi(a, b, 10))
print("Results:" +str(t))

Loop1
[ 0.6         2.27272727 -1.1         1.875     ]
Loop2
[ 1.04727273  1.71590909 -0.80522727  0.88522727]
Loop3
[ 0.93263636  2.05330579 -1.04934091  1.13088068]
Loop4
[ 1.01519876  1.95369576 -0.96810863  0.97384272]
Loop5
[ 0.9889913   2.01141473 -1.0102859   1.02135051]
Loop6
[ 1.00319865  1.99224126 -0.99452174  0.99443374]
Loop7
[ 0.99812847  2.00230688 -1.00197223  1.00359431]
Loop8
[ 1.00062513  1.9986703  -0.99903558  0.99888839]
Loop9
[ 0.99967415  2.00044767 -1.00036916  1.00061919]
Loop10
[ 1.0001186   1.99976795 -0.99982814  0.99978598]
Results:[ 1.0001186   1.99976795 -0.99982814  0.99978598]


Gauss-Seidel

In [ ]:
# Gauss-Seidel
def seidel(a, x ,b): 	 
	n = len(a)				 
	# for loop for 4 times as to calculate a,b,c,d 
	for j in range(0, n):		 
		# temp variable d to store b[j] 
		d = b[j]				 
		
		# to calculate respective ai, bi, ci, di 
		for i in range(0, n):	 
			if(j != i): 
				d-=a[j][i] * x[i] 
		# updating the value of our solution		 
		x[j] = d / a[j][j] 
	 
	return x	 



In [28]:
		 
# initial solution				 
x = [0, 0, 0, 0]			
#x=np.zeroes(4)
a=[[10, -1, 2, 0],[-1, 11, -1, 3],[2, -1, 10, -1],[0, 3, -1, 8]]
b = [6,25,-11,15] 
print(x) 

#loop run for m times depending on m the error value 
for i in range(0, 10):
  print("Loop "+ str(i+1))
  x = seidel(a, x, b) 
	#print each time the updated solution
  print(x)					 
line = "Result:\t"
print(line + str(x))

[0, 0, 0, 0]
Loop 1
[0.6, 2.3272727272727276, -0.9872727272727271, 0.8788636363636363]
Loop 2
[1.0301818181818183, 2.0369380165289255, -1.0144561983471074, 0.9843412190082644]
Loop 3
[1.006585041322314, 2.003555016904583, -1.002527384673178, 0.9983509455766342]
Loop 4
[1.000860978625094, 2.000298250656547, -1.0003072761017007, 0.9998497464910823]
Loop 5
[1.000091280285995, 2.000021342246459, -1.0000311471834449, 0.9999881032596473]
Loop 6
[1.0000083636613348, 2.0000011733362677, -1.0000027450726754, 0.9999992168648151]
Loop 7
[1.0000006663481618, 2.0000000246073673, -1.000000209122414, 0.9999999646319355]
Loop 8
[1.0000000442852195, 1.999999994660636, -1.0000000129277866, 1.0000000003862881]
Loop 9
[1.0000000020516209, 1.9999999989059065, -1.0000000004811047, 1.000000000350147]
Loop 10
[0.9999999999868117, 1.9999999998595697, -0.9999999999763907, 1.0000000000556126]
Result:	[0.9999999999868117, 1.9999999998595697, -0.9999999999763907, 1.0000000000556126]
